In [78]:
# PCA example     https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html

import numpy as np
from sklearn.decomposition import PCA
X = np.array([[-1, -1, 4], [-2, -1, 5], [-3, -2, 0], [1, 1, -1], [2, 1, 4], [3, 2, 1]])
pca = PCA()   # n_components = X
pca.fit(X)
print(pca.explained_variance_ratio_)
print(pca.singular_values_)
print(pca.components_)
X.shape

[0.59804448 0.39834126 0.00361426]
[6.50857004 5.31185835 0.50597452]
[[ 0.7488593   0.50110535 -0.43370864]
 [-0.38440989 -0.20465226 -0.90019248]
 [-0.53985071  0.84083939  0.0393741 ]]


(6, 3)

In [1]:
from myutils import *
import ftest as ft

run = 'FHA'

fileIndex = 1111    # dummy
filename = get_vlsvfile_fullpath(run, fileIndex)
f = ft.f(filename)
coords = f.read_variable("vg_coordinates")
coords.shape
RE = 6371000.
r_RE = np.linalg.norm(coords, axis = 1) / RE
x_RE = coords[:,0] / RE ; y_RE = coords[:,1] / RE ; z_RE = coords[:,2] / RE
#ind = np.where((x_RE > 0) & (x_RE < 15) & (y_RE > -15) & (y_RE < 15) & (z_RE > -15) & (z_RE < 15))[0]
ind = np.where(r_RE < 15)[0]


start = 1000
stop = 1200     # last: 1612
dct = timeseries(run, ['vg_J'], start, stop)
#dct = timeseries(run, ['vg_J', 'ig_fac', 'ig_inplanecurrent'], start, stop)

vg_J = dct['vg_J'][:,ind, :]
vg_J = dct['vg_J'].reshape([dct['vg_J'].shape[0], dct['vg_J'].shape[1] * dct['vg_J'].shape[2]]) 

# pre-process (because PCA is affected by scale). How do I convert back to physical units?
from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()
scaled_vg_J = std_scaler.fit_transform(vg_J)    # mean 0, standard deviation = 1

#vg_J = np.transpose( dct['vg_J'].reshape([dct['vg_J'].shape[0], dct['vg_J'].shape[1] * dct['vg_J'].shape[2]]) ).copy(order='C')
#ig_fac = dct['ig_fac']
#ig_inplanecurrent = dct['ig_inplanecurrent']

pca = PCA(n_components = 10)   # n_components = X
pca.fit(scaled_vg_J)
print(pca.explained_variance_ratio_)
print(pca.singular_values_)
print(pca.components_)



scaled_J_pca = pca.components_


Using backend module://matplotlib_inline.backend_inline
Using matplotlib version 3.7.1
Found population proton
Found population proton
Found population proton
Found population proton
Found population proton
Found population proton
Found population proton
Found population proton
Found population proton
Found population proton
Found population proton
Found population proton
Found population proton
Found population proton
Found population proton
Found population proton
Found population proton
Found population proton
Found population proton
Found population proton
Found population proton
Found population proton
Found population proton
Found population proton
Found population proton
Found population proton
Found population proton
Found population proton
Found population proton
Found population proton
Found population proton
Found population proton
Found population proton
Found population proton
Found population proton
Found population proton
Found population proton
Found population proton
F

NameError: name 'PCA' is not defined

In [77]:
scaled_J_pca[2,:]

array([ 0.00024023, -0.00027336, -0.00034256, ...,  0.00063827,
       -0.00028677,  0.00074625])

In [64]:
# pre-process (because PCA is affected by scale). How do I convert back to physical units?
from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()
scaled_vg_J = std_scaler.fit_transform(vg_J)    # mean 0, standard deviation = 1


array([[ 1.53554044e-10, -3.86075755e-10, -2.17495934e-11, ...,
         3.32106148e-11, -1.80750328e-11,  7.47984747e-12],
       [ 1.05234141e-10,  4.11101327e-11,  4.54930676e-11, ...,
         1.89514515e-11,  6.25782325e-12,  2.38815532e-13],
       [ 2.13213697e-10, -4.06829917e-11,  7.05816794e-11, ...,
         2.00040037e-11,  6.05291511e-12,  2.45520021e-13],
       ...,
       [ 1.91352392e-10, -3.27326805e-10, -3.37529900e-11, ...,
         7.18281250e-12, -2.94967365e-13,  1.43519842e-12],
       [ 5.82638191e-12, -1.28206222e-11, -5.76031453e-12, ...,
         8.42870131e-12, -4.97808663e-13,  1.98128926e-12],
       [ 5.60152869e-10, -1.03611608e-09,  6.44502229e-11, ...,
         9.57287027e-12, -6.74887284e-13,  2.59095154e-12]])

In [30]:
ind

array([      0,       1,       5, ..., 3966401, 3966402, 3966423])