In [12]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import matplotlib.gridspec as gridspec

output = pd.read_csv('pyamp_Control.csv', delim_whitespace = True)

output.keys()


Index(['Jd', 'mlat', 'mlt'], dtype='object')

In [15]:


#fig = plt.figure()
gs = gridspec.GridSpec(1, 2, width_ratios=[10,1])
#gs = gridspec.GridSpec(2, 1)
ax2 = plt.subplot(gs[0], projection="polar", aspect=1.)
#phi_plot = phi + (np.pi / 3)          # rotate by ninety-degrees so noon is at the top
#theta_plot = theta*181/np.pi

mask = (np.array(output['mlat']) > 0)

MLT = np.array(output['mlt'])[mask]
MLAT = np.array(output['mlat'])[mask]
J = np.array(output['Jd'])[mask]    # units?

phi_plot = MLT * 360 / 24.
theta_plot = 91. - MLAT 
phi_plot = phi_plot.reshape([100,100]) - 90. 
theta_plot = theta_plot.reshape([100,100])
J = J.reshape([100,100])


if np.nanmin(theta_plot) > 91:
    theta_plot = 181 - theta_plot
#im = ax2.pcolormesh(phi_plot*np.pi / 180, np.abs(theta_plot), J,
#                    cmap='bwr', shading='auto')            # north pole
im = ax2.contour(phi_plot*np.pi / 180, np.abs(theta_plot), J, 13, cmap='PRGn', vmin = -3., vmax = 3., linestyles = 'dashed');
#ax2.plot(phi_plot.flatten(), phi_plot.flatten() * 0 + 10)
ax2.set_ylim([0,40])
ax2.set_yticks([10, 20, 30])  # Less radial ticks
ax2.set_yticklabels([r'$80^\circ$', r'$70^\circ$', r'$60^\circ$'])
ax2.set_rlabel_position(-10)  # Move radial labels away from plotted line
ax2.set_xticks(list(np.arange(0, 2*np.pi, np.pi / 4)))
#ax2.set_xticklabels(list(np.arange(18, 24, 3)) + list(np.arange(0, 18, 3)))
ax2.set_xticklabels(list(np.arange(6, 24, 3)) + list(np.arange(0, 6, 3)))
ax2.grid(True)
ax3 = plt.subplot(gs[1])
   #cax = fig.add_axes([ax.get_position().x2+0.01,ax.get_position().y0,0.02,ax.get_position().height])
   #plt.colorbar(im, cax=cax) # Similar to fig.colorbar(im, cax = cax)
   #divider = make_axes_locatable(ax2)
   #cax = divider.append_axes('right', size='6%', pad=0.05)
   #cbar = fig.colorbar(im, cax=cax, orientation='vertical')
cbar = plt.colorbar(im, cax=ax3, aspect = 40)
   #cbar = mpl.colorbar.ColorbarBase(ax3, cmap = cmap)
cbar.set_label(r'J [$\mu A/m^3$]')
ax2.set_title('MFACE FAC')
#plt_temp = plt
#self.fig_list.append(plt_temp)
#self.fig_path_list.append(path)
plt.tight_layout()
#mkdir_path(path)
#plt.savefig(path)
plt.sca(ax2)   # set the current axis to the main plot 
plt.show()
plt.savefig('pyamps_FAC.png')
#if pltclose:   # set pltclose=false to plot on top ofthe figure?
#    plt.close()
plt.close()


In [14]:


fig, (ax0, ax1) = plt.subplots(2, 1)

c = ax0.pcolor(J)
ax0.set_title('default: no edges')

c = ax1.pcolor(phi_plot, theta_plot, J, edgecolors='k', linewidths=4, cmap='bwr')
ax1.set_title('thick edges')

fig.tight_layout()
plt.show()
plt.savefig('example.png')
plt.close()

In [4]:
np.min(output)
a, b = np.where(J>0)
b.shape

(5880,)

In [5]:
MLT.reshape([200,100])[:,0] * 360 / 24

ValueError: cannot reshape array of size 10000 into shape (200,100)

In [6]:
phi_plot[:,0]
phi_plot

array([[-89.9       , -89.9       , -89.9       , ..., -89.9       ,
        -89.9       , -89.9       ],
       [-86.26565657, -86.26565657, -86.26565657, ..., -86.26565657,
        -86.26565657, -86.26565657],
       [-82.63131313, -82.63131313, -82.63131313, ..., -82.63131313,
        -82.63131313, -82.63131313],
       ...,
       [262.63131313, 262.63131313, 262.63131313, ..., 262.63131313,
        262.63131313, 262.63131313],
       [266.26565657, 266.26565657, 266.26565657, ..., 266.26565657,
        266.26565657, 266.26565657],
       [269.9       , 269.9       , 269.9       , ..., 269.9       ,
        269.9       , 269.9       ]])

In [7]:

output

Jd       mlat        mlt
0     -0.033303  60.000000   0.006667
1     -0.037157  60.302929   0.006667
2     -0.043257  60.605859   0.006667
3     -0.052403  60.908788   0.006667
4     -0.065299  61.211717   0.006667
...         ...        ...        ...
19995 -0.030069 -88.778283  23.993333
19996 -0.030284 -89.081212  23.993333
19997 -0.028391 -89.384141  23.993333
19998 -0.024973 -89.687071  23.993333
19999 -0.020789 -89.990000  23.993333

[20000 rows x 3 columns]

In [8]:
plt.scatter(MLT, MLAT)
plt.show()

In [9]:
MLAT

array([60.        , 60.30292929, 60.60585859, ..., 89.38414141,
       89.68707071, 89.99      ])

In [10]:
MLAT[9950:10200]

array([75.14646465, 75.44939394, 75.75232323, 76.05525253, 76.35818182,
       76.66111111, 76.9640404 , 77.2669697 , 77.56989899, 77.87282828,
       78.17575758, 78.47868687, 78.78161616, 79.08454545, 79.38747475,
       79.69040404, 79.99333333, 80.29626263, 80.59919192, 80.90212121,
       81.20505051, 81.5079798 , 81.81090909, 82.11383838, 82.41676768,
       82.71969697, 83.02262626, 83.32555556, 83.62848485, 83.93141414,
       84.23434343, 84.53727273, 84.84020202, 85.14313131, 85.44606061,
       85.7489899 , 86.05191919, 86.35484848, 86.65777778, 86.96070707,
       87.26363636, 87.56656566, 87.86949495, 88.17242424, 88.47535354,
       88.77828283, 89.08121212, 89.38414141, 89.68707071, 89.99      ])

In [11]:
MLAT[MLAT > 0]
MLAT.shape

(10000,)